version: '2'
services:
  repl:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app/Repl
    command: swift run
    privileged: true
  tests:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: swift test
  format:
    build:
        context: .
        dockerfile: Dockerfile.swiftformat
    volumes:
      - .:/app
    working_dir: /app
    command: swiftformat .

