name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode_27.0.app/Contents/Developer

jobs:
  test:

    runs-on: xcode-27
    env:
      working_directory: ./

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      working-directory: ${{env.working_directory}}
    - name: Run tests
      run: swift test -v
      working-directory: ${{env.working_directory}}

  format:

    runs-on: xcode-27

    steps:
     - uses: actions/checkout@v2
     - name: Run swift-format lint
	   run: swift format lint --recursive .

  repl:

    runs-on: xcode-27
    env:
      working_directory: ./Repl

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      working-directory: ${{env.working_directory}}
      
  test-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/swift-test-docker
