name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

jobs:
  test:

    runs-on: macos-latest
    env:
      working_directory: ./

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      working-directory: ${{env.working_directory}}
    - name: Run tests
      run: swift test -v
      working-directory: ${{env.working_directory}}

  format:

    runs-on: macos-latest

    steps:
     - name: Install Mint
       run: brew install mint
     - name: Install SwiftFormat
       run: mint install nicklockwood/SwiftFormat@0.46.2
     - uses: actions/checkout@v2
     - name: Run SwiftFormat lint
       run: swiftformat --lint .

  repl:

    runs-on: macos-latest
    env:
      working_directory: ./Repl

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      working-directory: ${{env.working_directory}}
